FROM ros:humble-perception

RUN apt-get update && apt-get install -y \
    nano \
    python3-pip \
    python3-colcon-common-extensions \
    python3-opencv \
    ros-humble-cv-bridge \
    ros-humble-rmw-cyclonedds-cpp \
    && rm -rf /var/lib/apt/lists/*

# (Safety) C의 UART Bridge용
RUN pip3 install pyserial

WORKDIR /ros2_ws
RUN echo "source /opt/ros/humble/setup.bash" >> ~/.bashrc
